language: java
sudo: required
dist: trusty

before_install:
 - "export JAVA_OPTS='-Xmx1024m -XX:MaxPermSize=256m'"

jdk:
 - oraclejdk8

install: ./gradlew assemble -s
script: ./gradlew check funcTest install -s --continue && jdk_switcher use oraclejdk8 && ./scripts/runTests.sh
